#! /bin/bash

cd $( dirname $0 )

EC2="../../utils/ec2"


if [ ! -d ./results ]; then
	mkdir results
fi


# Args: <Coordserver-Port> <Weightserver-IP> <Weightserver-Port> <Dataserver-Port>
./build/lambda_sample 55430 $(${EC2} prip) 55432 55431
