#! /bin/bash

cd $( dirname $0 )

EC2="../../utils/ec2"


if [ ! -d ./results ]; then
	mkdir results
fi


# Args: <Coordserver-Port> <Weightserver fILE> <Dataserver-Port>
./build/lambda_sample 12430 "weightservers" 12431
