#! /bin/bash

ASP_DIR=/home/ubuntu/aspire-streaming

cd ${ASP_DIR}

function header {
	echo -e "\e[33;1m######## ${1} ########\e[0m"
}

header "BUILDING $1"
./bld $1

if [ $? -ne 0 ]; then
	exit
fi

header "RUNNING"
./run/ec2run.sh $1
