#!/bin/bash

##
## Install AWS SDK
##


cd ${HOME}

sudo apt install libcurl4-openssl-dev libssl-dev

# Install AWS-SDK.
if [[ ! $( ldconfig -p | grep aws-cpp-sdk ) ]]; then    # Only install if not installed yet.
    git clone https://github.com/aws/aws-sdk-cpp.git
    cd aws-sdk-cpp
    mkdir build
    cd build
    cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY=lambda -DBUILD_SHARED_LIBS=OFF
    make
    sudo make install
    cd ../..
    rm -rf aws-sdk-cpp
fi
