#!/bin/bash

##
## Install requried dependencies on a graph server. TO be invoked on the remote machine.
##


# Basic packages.
cd ${HOME}/gnn-lambda/gnnman/helpers/
source basic.install


# ZeroMQ stuff.
cd ${HOME}/gnn-lambda/gnnman/helpers/
source zmq.install


# BLAS stuff.
cd ${HOME}/gnn-lambda/gnnman/helpers/
source blas.install

# AWSSDK Install
cd ${HOME}/gnn-lambda/gnnman/helpers/
source aws-sdk-cpp.install
