#!/bin/bash

##
## Send a file to all the nodes specified in `~/dshmachines`. TO be invoked on the remote machine.
## Must have achieved passwd-less ssh among friend machines.
##
## File path should be specified relative to `dorylus/` directory.
##


cd ${HOME}/dorylus/

EC2MAN_CMD="python3 -m ec2man"


FILE=$( pwd )/$1

for MACH in $( cat ~/dshmachines ); do
    ssh ${MACH} "mkdir -p $( dirname ${FILE} )"
    scp -q ${FILE} ${MACH}:${FILE}
done
