#!/bin/bash

##
## Send a file to all the nodes specified in `~/dshmachines`. TO be invoked on the remote machine.
## Must have achieved passwd-less ssh among friend machines.
##
## File path should be specified relative to `gnn-lambda/` directory.
##


cd ${HOME}/gnn-lambda/

EC2MAN_CMD="python3 -m ec2man"


FILE=$( pwd )/$1

for MACH in $( cat ~/dshmachines ); do
    scp -q ${FILE} ${MACH}:${FILE}
done
