#!/bin/bash

##
## Install requried dependencies on a machine that can compile and manage lambda functions.
##


# Basic packages.
cd ${HOME}/gnn-lambda/gnnman/helpers/
source basic.install


# ZeroMQ stuff.
cd ${HOME}/gnn-lambda/gnnman/helpers/
source zmq.install


# AWS API stuff.
cd ${HOME}/gnn-lambda/gnnman/helpers/
source aws.install


# BLAS stuff.
cd ${HOME}/gnn-lambda/gnnman/helpers/
source blas.install
