#!/bin/bash

#
# Convert a text graph into binary, and partite it into partitions.
#

if [ ! $# == 6 ]; then
    echo "Usage: $0 <GraphFile> <Undirected? (0/1)> <NumVertices> <NumPartitions> <FeatureFile> <DimFeatures>"
    exit
fi

rm -rf data && mkdir data

function header {
    echo -e "\e[33;1m######## ${1} ########\e[0m"
}


#
# Convert the graph to binary snap.
#

GRAPH=$1
UNDIRECTED=$2
VERTICES=$3
PARTS=$4

header "Converting the graph to binary..."

./graphtobinary ${GRAPH} --snapfile=${GRAPH} --undirected=${UNDIRECTED} --header=1

BSNAP=${GRAPH}.bsnap
mv ${BSNAP} .
BSNAP=$( basename ${BSNAP} )

header "Conduct partitioning..."

./partitioner ${BSNAP} ${VERTICES} ${PARTS}

mv parts_${PARTS} data/
mv ${BSNAP} data/

ln -s ../${BSNAP} data/parts_${PARTS}/${BSNAP}.edges


#
# Convert the features file to binary snap.
#

FEATURES=$5
DIMFEAT=$6

header "Converting the features file to binary..."

./featurestobinary --featurefile=${FEATURES} --featuredimension=${DIMFEAT}


chmod -R a+w data

echo -e "\e[32;1mDataset under 'data/' folder is ready for battle.\e[0m"
