#!/bin/bash

##
## Convert a text graph into binary snaps, and partite it into partitions.
## Convert the features file into bsnap as well.
##
## Output is located in `inputs/data` folder. The dataset inside is ready to be used as our system's input.
##


if [ ! $# == 8 ]; then
    echo "Usage: $0 <GraphFile> <Undirected? (0/1)> <NumVertices> <NumPartitions> <FeaturesFile> <DimFeatures> <LabelsFile> <LabelKinds>"
    exit
fi

rm -rf data && mkdir data


#
# Convert the graph to binary snap.
#

GRAPH=$1
UNDIRECTED=$2
VERTICES=$3
PARTS=$4

echo "Converting the graph to binary..."

./graphtobinary ${GRAPH} --snapfile=${GRAPH} --undirected=${UNDIRECTED} --header=1
mv ${GRAPH}.bsnap ./graph.bsnap

echo
echo "Conduct partitioning..."

./partitioner graph.bsnap ${VERTICES} ${PARTS}
if [[ ! $? == 0 ]]; then
    exit 1
fi

mv parts_${PARTS} data/
mv graph.bsnap data/

ln -s ../graph.bsnap data/parts_${PARTS}/graph.bsnap.edges


#
# Convert the features file to binary snap.
#

FEATURES=$5
DIMFEATS=$6

echo
echo "Converting the features file to binary..."

./featurestobinary --featuresfile=${FEATURES} --featuredimension=${DIMFEATS}
if [[ ! $? == 0 ]]; then
    exit 1
fi

mv ${FEATURES}.bsnap data/features.bsnap


#
# Convert the labels file to binary snap.
#

LABELS=$7
LABELKINDS=$8

echo
echo "Converting the labels file to binary.."

./labelstobinary --labelsfile=${LABELS} --labelkinds=${LABELKINDS}
if [[ ! $? == 0 ]]; then
    exit 1
fi

mv ${LABELS}.bsnap data/labels.bsnap


# Permissions stuff...
chmod -R a+w data

echo
echo -e "Dataset under 'data/' folder is ready for battle."
