#!/bin/bash

##
## Convert a text graph into binary snaps, and partite it into partitions.
## Convert the features file into bsnap as well.
##
## Output is located in `inputs/data` folder. The dataset inside is ready to be used as our system's input.
##


function header {
    echo -e "\e[33;1m${1}\e[0m"
}


if [ ! $# == 6 ]; then
    echo "Usage: $0 <GraphFile> <Undirected? (0/1)> <NumVertices> <NumPartitions> <FeatureFile> <DimFeatures>"
    exit
fi

rm -rf data && mkdir data


#
# Convert the graph to binary snap.
#

GRAPH=$1
UNDIRECTED=$2
VERTICES=$3
PARTS=$4

header "Converting the graph to binary..."

./graphtobinary ${GRAPH} --snapfile=${GRAPH} --undirected=${UNDIRECTED} --header=1

GRAPH_BSNAP=${GRAPH}.bsnap
mv ${GRAPH_BSNAP} .
GRAPH_BSNAP=$( basename ${GRAPH_BSNAP} )

header "Conduct partitioning..."

./partitioner ${GRAPH_BSNAP} ${VERTICES} ${PARTS}

mv parts_${PARTS} data/
mv ${GRAPH_BSNAP} data/

ln -s ../${GRAPH_BSNAP} data/parts_${PARTS}/${GRAPH_BSNAP}.edges


#
# Convert the features file to binary snap.
#

FEATURES=$5
DIMFEATS=$6

header "Converting the features file to binary..."

./featurestobinary --featurefile=${FEATURES} --featuredimension=${DIMFEATS}

FEATURES_BSNAP=${FEATURES}.bsnap

mv ${FEATURES_BSNAP} data/


chmod -R a+w data

echo -e "\e[32;1mDataset under 'data/' folder is ready for battle.\e[0m"
