#!/bin/bash

##
## Build the system on 3 master nodes, and send the executable to all the other machines listed in ec2 manager.
## Must be invoked after a proper `setup-cluster`!!!
##
## Usage: $ ./gnnman/build-system
##
## Options:
##      Default: Build the corresponding server on master nodes (0), and send the executable to all other machiens.
##


cd $( dirname $0 )/..

EC2MAN_CMD="python3 -m ec2man"


# For graph servers.
echo "Processing context 'graph'..."
${EC2MAN_CMD} graph 0 ssh -t "cd gnn-lambda && ./gnnman/helpers/graphserver.bld && ./gnnman/helpers/send-file build/graphserver"


# For graph servers.
echo "Processing context 'weight'..."
${EC2MAN_CMD} weight 0 ssh -t "cd gnn-lambda && ./gnnman/helpers/weightserver.bld && ./gnnman/helpers/send-file build/weightserver"


# For coordination servers. Normally only one coordination server, so no need to send out.
echo "Processing context 'coord'..."
${EC2MAN_CMD} coord 0 ssh -t "cd gnn-lambda && ./gnnman/helpers/coordserver.bld"
