#!/bin/bash

##
## Build the system on 3 master nodes, and send the executable to all the other machines listed in ec2 manager.
## Must be invoked after a proper `setup-cluster`!!!
##
## Usage: $ ./gnnman/build-system [Context]
##
## Options:
##      Default: Build the corresponding server on master nodes (0), and send the executable to all other machiens.
##      Context: If given, only build the specified context
##


cd $( dirname $0 )/..

EC2MAN_CMD="python3 -m ec2man"


if [[ ! -z $1 ]] && [[ $1 != "graph" ]] && [[ $1 != "weight" ]] && [[ $1 != "gpu" ]]; then
    echo "Context '$1' not recognized."
    echo "Usage: ./gnnman/build-system [[Context|gpu]...]    # Empty means build all."
    exit 1
fi

let BUILD_GRAPH=0
let BUILD_WEIGHT=0
BUILD_GPU_OPT=''
if [[ $1 == "gpu" ]]; then
    BUILD_GRAPH=1
    BUILD_WEIGHT=1
    BUILD_GPU_OPT='gpu'
elif [[ $1 == "graph" ]]; then
    BUILD_GRAPH=1
    if [[ $2 == "gpu" ]]; then
        BUILD_GPU_OPT='gpu'
    fi
elif [[ $1 == "weight" ]]; then
    BUILD_WEIGHT=1
fi

# For graph servers.
if [ ${BUILD_GRAPH} -eq 1 ]; then
    echo "Processing context 'graph'..."
    ${EC2MAN_CMD} graph 0 ssh -t "cd gnn-lambda && ./gnnman/helpers/graphserver.bld ${BUILD_GPU_OPT} && ./gnnman/helpers/send-folder build"
fi


# For weight servers.
if [ ${BUILD_WEIGHT} -eq 1 ]; then
    echo "Processing context 'weight'..."
    ${EC2MAN_CMD} weight 0 ssh -t "cd gnn-lambda && ./gnnman/helpers/weightserver.bld && ./gnnman/helpers/send-folder build"
fi
