#!/bin/bash

##
## Send the source code folder to all the machines listed in ec2 manager.
##
## Usage: $ ./gnnman/send-source [--force]
##
## Options:
##      Default: Use `rsync` to send the updates on local `dorylus/` folder to all remote machines.
##      --force: Force to delete the existing `~/dorylus/` folder on remote machines, and send a completely new copy.
##


cd $( dirname $0 )/..

EC2MAN_CMD="python3 -m ec2man"


# Loop through all three contexts.
for CTX in graph weight; do

    echo "Processing context '${CTX}'..."

    # If in force mode, delete existing repo.
    if [[ $1 == "--force" ]]; then
        echo "Deleting existing repo..."
        ${EC2MAN_CMD} ${CTX} all ssh "rm -rf dorylus/"
    fi

    # Send repo updates using `rsync`.
    echo "Sending new updates..."
    ${EC2MAN_CMD} ${CTX} all rsync -zz --exclude ".git*" --exclude "wiki" --exclude "README.md" --exclude "data" --exclude "miscs" --exclude "inputs" --exclude "results" ../dorylus &

done


# Wait for background commands to finish.
echo "Waiting on background sending to finish..."
wait
