#!/bin/bash

## Similar to setup-cluster except this one is used for machines with GPU and weight server only
## Usage: $ ./gnnman/setup-cluster-gpu
##
## All these config files are put in the home directory `~/` for convience.
##

#for GPU machines
cd $( dirname $0 )/..

EC2MAN_CMD="python3 -m ec2man"
USERNAME=`whoami`
dshfile=~/dshmachines

if [ ! -f $dshfile ] ; then
	echo "You need to write $dshfile file manually"
	exit 1
fi
# Start all machines...
${EC2MAN_CMD} weight all start

rm -f ~/wserverip
${EC2MAN_CMD} weight all pubip > wserverip

# For graph servers.
echo "Processing context 'graph'..."
echo "0.0.0.0" > cserverip #just a placeholder
requiredFiles="$HOME/dshmachines wserverip cserverip run/layerconfig run/cserverport run/gserverport run/dataport run/ctrlport run/nodeport run/wserverport"
machineList=$( < ~/dshmachines )
for machine in $machineList
do 
	scp $requiredFiles $machine:~ 
done
rm -f cserverip
for machine in $machineList
do 
	echo $machine| sed 's/.*@\(.*\)/\1/'>myprip
	cp myprip mypubip
	scp mypubip $machine:~
	scp myprip $machine:~
done
rm -f myprip mypubip
rm -f wserverip

# For weight servers.
echo "Processing context 'weight'..."
NUM_GRAPH_NODES=$(( $( ${EC2MAN_CMD} weight info | wc -l | awk '{print $1}' ) - 1 ))
for i in $( seq 0 $(( ${NUM_GRAPH_NODES} - 1 )) ); do
    ${EC2MAN_CMD} weight $i prip > myprip
    ${EC2MAN_CMD} weight $i put myprip
    rm -f myprip
done

${EC2MAN_CMD} weight dshfile > dshmachines
${EC2MAN_CMD} weight all put dshmachines run/dataport run/layerconfig run/wserverport
rm -f dshmachines
