#! /bin/bash

##
## Try invoking the registered lambda functions.
##

EC2="../../../scripts/ec2"

function invoke {
	id=$1
	pub_ip=$( ${EC2} pubip )
	payload="{ \"weightserver\" : \"${pub_ip}\", \"dataserver\" : \"${pub_ip}\", \"wport\" : \"65432\", \"dport\" : \"65431\", \"layer\" : 0, \"id\" : $id }"
	aws lambda invoke --function-name matmul-cpp --payload "$payload" output-files/outfile$id.txt

	cat output-files/outfile$id.txt
	echo
}

reqs=${1}
threads=${reqs:=1}
((threads--))

for i in $( seq 0 ${threads} ); do
	invoke $i &
done
