#! /bin/bash

## BUILD AND RUN ##
## Calls the build script for a specific benchmark, distributes the 
## executable to the cluster, then runs it with the specified BM
## 	--The option provided needs to correspond to options in the
##	  build and run scripts

#
# Usage: ./b+r [Dataset] [Feature-File]
#
#   Dataset:        small(*), fb
#   Feature-File:   (*), path_to_file 
#
# "(*)" means default.
#

cd $( dirname $0 )

function header {
	echo -e "\e[34;1m######## ${1} ########\e[0m"
}


header "BUILDING"

./bld

if [ $? -ne 0 ]; then
	exit
fi


header "RUNNING"

./run $1 $2 $3
