#! /bin/bash

## BUILD AND RUN ##
## Calls the build script for a specific benchmark, distributes the 
## executable to the cluster, then runs it with the specified BM
## 	--The option provided needs to correspond to options in the
##	  build and run scripts

#
# Usage: ./b+r [Bench] [Dataset] [Feature-File]
#
#   Bench:          agg(*)
#   Dataset:        fb(*), small
#   Feature-File:   (*), path_to_file 
#
# "(*)" means default.
#

cd $( dirname $0 )

function header {
	echo -e "\e[32;1m######## ${1} ########\e[0m"
}

header "BUILDING the engine & benchmark"
./bld $1

if [ $? -ne 0 ]; then
	exit
fi

header "RUNNING the benchmark"
cd ..
./run/ec2run.sh $1 $2 $3
