#! /bin/bash

## BUILD AND RUN ##
## Calls the build script for a specific benchmark, distributes the 
## executable to the cluster, then runs it with the specified BM
## 	--The option provided needs to correspond to options in the
##	  build and run scripts

#
# Usage: ./b+r [Dataset] [Feature-File]
#
#   Dataset:        small(*), fb
#   Feature-File:   (*), path_to_file 
#
# "(*)" means default.
#

cd $( dirname $0 )

function header {
	echo -e "\e[32;1m######## ${1} ########\e[0m"
}

function prompt {
    echo -e "\e[33;1m${1}\e[0m"
}


header "BUILDING"

./bld

if [ $? -ne 0 ]; then
	exit
fi


header "RUNNING"

case $1 in
    "small")
        prompt "Running on dataset \"small\"."
        ;;
    "fb")
        prompt "Running on dataset \"fb\"."
        ;;
    *)
        prompt "Running on the default dataset (\"small\")."
        ;;
esac

cd ..

if [ -e $2 ]; then
    prompt "Initial features file to be loaded: \"$2\""
    ./run/ec2run.sh $1 $2
else
    prompt "Using default initial features file: \"parts_x/../features\""
    ./run/ec2run.sh $1
fi
        