#! /bin/bash

## BUILD SCRIPT ##
## Given an option, build the executable and distribute the script across the 
## cluster
##	--Most commonly used have abbreviated opts but full make command can 
##	  be provided
##	--If adding another option to case, should correspond with option in 
##	  b+r to build and run benchmark
##	Note: File could definitely be cleaned up...

ASPIRE_DIR=/home/jothor/aspire-streaming
BUILD_DIR=${ASPIRE_DIR}/build
UTILS_DIR=${ASPIRE_DIR}/utils

cd ${BUILD_DIR}

case $1 in
	"re")
		make clean; make
		;;
	"inc")
		make increment
		
		if [ $? -eq 0 ]; then 
			cd ${ASPIRE_DIR}
			./utils/send_file build/increment.bin
		else 
			return 13
		fi
		;;
	"agg")
		make aggregate
		if [ $? -eq 0 ]; then 
			cd ${ASPIRE_DIR}
			./utils/send_file build/aggregate.bin
		else 
			return 13
		fi
		;;
	*)
		make $1
		;;
esac

