#! /bin/bash

## BUILD SCRIPT ##
## Given an option, build the executable and distribute the script across the 
## cluster
##	--Most commonly used have abbreviated opts but full make command can 
##	  be provided
##	--If adding another option to case, should correspond with option in 
##	  b+r to build and run benchmark
##	Note: File could definitely be cleaned up...

cd $( dirname $0 )/../build

case $1 in
	"agg")
		make clean; make mode=debug aggregate

		if [ $? -eq 0 ]; then 
			cd ..
			./utils/send_file build/aggregate.bin
		else 
			return 13
		fi
		;;
	"inc")
		make clean; make mode=debug increment

		if [ $? -eq 0 ]; then 
			cd ..
			./utils/send_file build/increment.bin
		else 
			return 13
		fi
		;;
	"load")
		make clean; make mode=debug loadfeatures

		if [ $? -eq 0 ]; then 
			cd ..
			./utils/send_file build/loadfeatures.bin
		else 
			return 13
		fi
		;;
	*)
		make clean; make mode=debug aggregate

		if [ $? -eq 0 ]; then 
			cd ..
			./utils/send_file build/aggregate.bin
		else 
			return 13
		fi
		;;
esac

