#! /bin/bash

## BUILD SCRIPT ##
## Given an option, build the executable and distribute the script across the 
## cluster
##	--Most commonly used have abbreviated opts but full make command can 
##	  be provided
##	--If adding another option to case, should correspond with option in 
##	  b+r to build and run benchmark
##	Note: File could definitely be cleaned up...

cd $( dirname $0 )

if [[ ${1} == "coord" ]]; then
    cd ../src/coordination-server/
    ./bld

elif [[ ${1} == "weights" ]]; then
    cd ../src/weight-server/
    ./bld

    cd ~/gnn-lambda/
    ./utils/send_file build/weight_server
    
else
    cd ../build

    make clean

    if [[ ${1} == "debug" ]]; then
        make -s mode=debug
    else
        make -s mode=release
    fi

    if [ $? -eq 0 ]; then 
        cd ..
        ./utils/send_file build/gnn-lambda.bin
        echo -e "\e[92;1mSuccessfully built the system, congrats ;)\e[0m"
    else
        echo -e "\e[91;1mBuild failed!\e[0m"
        exit 1
    fi
fi
