#! /bin/bash



id=$( cat ~/.aws/id )

case $1 in 
	"id")
		echo $id
		;;
	"pubip")
		aws ec2 describe-instances --instance-ids $id --query 'Reservations[*].Instances[*].PublicIpAddress' --output text
		;;
	"prip")
		aws ec2 describe-instances --instance-ids $id --query 'Reservations[*].Instances[*].PrivateIpAddress' --output text
		;;
	"arn")
		echo arn:aws:iam::754699445878:role/lambda-cpp-demo
		;;
	"start")
		aws ec2 start-instances --instance-ids $id
		;;
	"stop")
		aws ec2 stop-instances --instance-ids $id
		;;
	"check")
		aws ec2 describe-instances --instance-ids $id --query 'Reservations[*].Instances[*].State' --output text
		;;
	"help")
		echo "Usage: ec2 [id|ip|arn|start|stop|check]"
		;;
	*)
		echo "Unrecognized option $1"
		;;
esac

