#! /bin/bash

## RUN ##
## Run the "ec2run.sh" script with prompts.

#
# Usage: ./run [Dataset] [Feature-File] [Layer-File]
#
#   Dataset:        small(*), fb
#   Feature-File:   (*), path_to_file
#   Layer-File:     (*), path_to_file
#
# "(*)" means default.
#

cd $( dirname $0 )/..

function prompt {
    echo -e "\e[33;1m${1}\e[0m"
}


case $1 in
    "small")
        prompt "Running on dataset \"small\"."
        ;;
    "fb")
        prompt "Running on dataset \"fb\"."
        ;;
    *)
        prompt "Running on the default dataset (\"small\")."
        ;;
esac

prompt "Using features file: \"parts_x/../features\"."

prompt "Using layer configuration file: \"parts_x/../layerconfig\"."

     
./run/ec2run.sh $1
