#! /bin/bash

cd $( dirname $0 )

EC2="../../utils/ec2"


if [ ! -d ./results ]; then
	mkdir results
fi


# Args: <Coordserver-Port> <Weightserver-IP> <Weightserver-Port> <Dataserver-Port>
../build/lambda_sample 65430 $( ${EC2} pubip ) 65432 65431
