#! /bin/bash

cd $( dirname $0 )

weightServerAddrFile=$1
weightServerAddrFile=${weightServerAddrFile:=wserverinfo}

if [ ! -d ~/coord_output ]; then
	mkdir ~/coord_output
fi

i=0
OUTFILE=~/coord_output/run

while [ -f ${OUTFILE}.$i ]; do
	((i++))
done

OUTFILE=${OUTFILE}.$i

numWghtServs=$(cat ${weightServerAddrFile} | wc -l)

echo "Running with ${numWghtServs} weight servers"
echo "Running with ${numWghtServs} weight servers" > ${OUTFILE}
# Args: <Coordserver-Port> <WeightserverAddress-File> <Weightserver-Port> <Dataserver-Port>
../build/coordination_server 55430 ${weightServerAddrFile} 55432 55431 >> ${OUTFILE}
