#! /bin/bash

WEIGHTSERVER={{user}}@{{WSERVER0}}
GRAPHSERVER={{user}}@{{GSERVER0}}

cd ${HOME}
dsh -m ${GRAPHSERVER} "./gnn-lambda/run/kill-zombies graph"
dsh -m ${WEIGHTSERVER} "./gnn-lambda/run/kill-zombies weight"
