#! /bin/bash

cd $( dirname $0 )

configFile=$1
dshFile=~/gnn-lambda/run/dshmachines

numNodes=$( cat ${dshFile} | wc -l )

if [ ! -d ~/weightserver_output ]; then
	mkdir ~/weightserver_output
fi

outputFile=~/weightserver_output/run
i=0

while [ -f ${outputFile}.${i} ]; do
	((i++))
done
outputFile=${outputFile}.${i}

echo "Running with ${numNodes} weight servers" > ${outputFile}

# Args: <Weightserver-Port> <Layerconfig-File>
dsh -M -f ${dshFile} "cd ~/gnn-lambda/; ./build/weight_server 55432 ${configFile:=run/layerconfig}" >> ${outputFile}
