#! /bin/bash

cd $(dirname "$0")

if [ ! -d build ]; then
	mkdir build
fi

cd build

echo -e "\e[33;1m### BUILDING ###\e[0m"
cmake .. -DCMAKE_BUILD_TYPE=Release

if [ $? -eq 0 ]; then
	make
fi	

if [ $? -eq 0 ]; then 
	case $1 in
		"pkg")
			make aws-lambda-package-forward-prop-shen
			;;
	esac
fi

if [ $? -eq 0 ]; then
	case $2 in
		"up")
			../update
			;;
	esac
fi
